# Generated by Django 5.2.2 on 2025-06-10 09:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this refund request', unique=True)),
                ('recipient_name', models.CharField(default='customer', help_text='Name of the person receiving the refund', max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount to be refunded', max_digits=10)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'Account number must be at least 8 characters'), django.core.validators.MaxLengthValidator(50, 'Account number cannot exceed 50 characters')])),
                ('card_number', models.CharField(help_text='Credit/Debit card number', max_length=19, validators=[django.core.validators.RegexValidator(message='Card number must be 13-19 characters (digits and spaces only)', regex='^[\\d\\s]{13,19}$')])),
                ('expiry_date', models.CharField(help_text='Card expiry date in YYYY-MM format', max_length=7, validators=[django.core.validators.RegexValidator(message='Expiry date must be in YYYY-MM format', regex='^\\d{4}-\\d{2}$')])),
                ('cvv', models.CharField(help_text='Card CVV/CVC code', max_length=4, validators=[django.core.validators.RegexValidator(message='CVV must be 3 or 4 digits', regex='^\\d{3,4}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the refund request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the refund request was last updated')),
                ('processed', models.BooleanField(default=False, help_text='Whether the refund has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the requester')),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
